#!/usr/bin/env python

import sys

argc = len(sys.argv)

if argc == 1:
    sys.stdout.write("0\n")
elif argc == 2 and "*" in sys.argv[1]:
    sys.stdout.write("0\n")
else:
    sys.stdout.write("{}\n".format(argc - 1))
